#!/usr/bin/env bash
######################################################################
# .what = the desert theme — for COSMIC's own shell, and for GTK apps
#
#   - it holds no `provision` phase: `cosmic.theme.ron` is TRACKED in this dir
#   - so there is no upstream to fetch and no version to pin
#
# ⚠️ .the .ron is the SINGLE source, and no css is copied
#   - COSMIC derives `~/.config/gtk-4.0/cosmic/dark.css` from the imported .ron
#   - it stamps that file `/* GENERATED BY COSMIC */` and regenerates it
#   - so a copy of `src/cosmic.gtk.desert.css` (unowned, left at the src/ root) over that
#     path never survives
#   - that css is read by no code, and is a human's asset to retire
#
#   - a GTK3 link is still owed, since COSMIC stops at the GTK4 stylesheet
#   - GTK3 apps read `~/.config/gtk-3.0/gtk.css` and would find no theme
#
# usage:
#   rhx grove.provision --what 3.2.theme --mode apply
######################################################################

grove_provision_3_2_theme() {
  bundle.upgrade 3.2.theme.configure.upsert
  bundle.upgrade 3.2.theme.configure.verify
}
