#!/usr/bin/env bash
######################################################################
# .what = apply the desert theme to COSMIC, and to GTK3/GTK4 apps
#
# ⚠️ .every path reads $GROVE_SRC
#   - a hardcoded `$HOME/git/more/dev-env-setup/src/...` names the MAIN checkout
#   - from a worktree that dresses one box from two commits at once
#   - (howto.install-configs-from-a-worktree)
#
# .the GTK3 file is a SYMLINK to the GTK4 one
#   - both toolkits read the same stylesheet
#   - a link makes the two impossible to diverge
#
# guarantee
#   - idempotent: `cp` and `ln -sf` converge, so a re-run rewrites identical bytes
#   - it DECLINES where no compositor exists
######################################################################

grove_provision_3_2_theme_configure_upsert() {
  if [[ "$GROVE_ENV_SERVER" != local@* ]]; then
    echo "   🌙 declined — a theme is read by a compositor and by GTK apps, and"
    echo "      $GROVE_ENV_SERVER runs neither"
    return 0
  fi

  local failed=0

  ####################################################################
  # 1. COSMIC's own surfaces
  ####################################################################
  local ron="$GROVE_SRC/grove.provision/3.cosmic/3.2.theme/cosmic.theme.ron"
  if [[ ! -f "$ron" ]]; then
    echo "   ✋ no theme at $ron" >&2
    echo "      ⇒ this run's own checkout is incomplete" >&2
    return 1
  fi

  if command -v cosmic-settings >/dev/null 2>&1; then
    if cosmic-settings appearance import "$ron" </dev/null; then
      echo "   • cosmic desert theme applied"
    else
      echo "   ✋ cosmic-settings refused the theme at $ron" >&2
      failed=1
    fi
  else
    echo "   🌙 cosmic-settings is absent, so the shell theme was not applied"
  fi

  ####################################################################
  # 2. point GTK3 at the GTK4 stylesheet COSMIC generates
  #
  # ⚠️ .this does NOT copy a stylesheet from the repo
  #   - COSMIC REGENERATES `~/.config/gtk-4.0/cosmic/dark.css` from the imported .ron
  #   - 📜 the live file opens `/* GENERATED BY COSMIC */` and holds 106 lines
  #   - 📜 the repo copy held 60, in the same desert palette, and never survived
  #   - a verify that compared the two would report drift on a healthy box
  #   - ⇒ the .ron is the single source (rule.require.solve-at-cause)
  #
  # .the LINK is the whole job here
  #   - COSMIC generates a GTK4 stylesheet and stops
  #   - GTK3 apps read ~/.config/gtk-3.0/gtk.css and would find no theme
  ####################################################################
  local gtk4="$HOME/.config/gtk-4.0/cosmic/dark.css"
  local gtk3="$HOME/.config/gtk-3.0"
  mkdir -p "$gtk3" || return 1

  if [[ ! -f "$gtk4" ]]; then
    echo "   🌙 COSMIC has not generated $gtk4 yet, so GTK3 has no stylesheet"
    echo "      to point at. it appears after the shell theme applies"
    return $failed
  fi

  ln -sf "$gtk4" "$gtk3/gtk.css" || return 1
  echo "   • GTK3 points at COSMIC's generated stylesheet (restart a GTK app)"

  return $failed
}
