#!/usr/bin/env bash
######################################################################
# .what = prove this box holds a usable keypair — both halves, and a private half
#         no other user can read
#
# .why BOTH halves are asserted
#   - a private key with no `.pub` cannot be registered with a remote
#   - a `.pub` with no private half is an identity you cannot present
#   - ⇒ either alone reads as "a key exists" to a file test
#   - and fails at the first connection
#
# .why the PERMISSION is a claim of its own
#   - ssh REFUSES a private key whose mode is group- or world-readable
#   - it prints "UNPROTECTED PRIVATE KEY FILE" and ignores the key entirely
#   - ⇒ a too-open mode is a key that does not work, not a hygiene nitpick
#   - the symptom is "the remote asks for a password", never "the key file is 0644"
#   - a `cp -r` of a dotfile tree is the usual cause
#
# guarantee:
#   - READ-ONLY. it stats files and reads no key material
#
# exit:
#   0 = a keypair exists, with a private half only this user can read
#   1 = a claim failed, and which is named
######################################################################

grove_provision_2_3_ssh_configure_verify() {
  local failed=0
  local key_dir="$HOME/.ssh"

  ####################################################################
  # 1. a keypair — both halves, of any of the three usual types
  ####################################################################
  local found=""
  local candidate
  for candidate in id_ed25519 id_ecdsa id_rsa; do
    if [[ -f "$key_dir/$candidate" && -f "$key_dir/$candidate.pub" ]]; then
      found="$candidate"; break
    fi
  done

  if [[ -n "$found" ]]; then
    echo "   • ssh keypair present (~/.ssh/$found + .pub) ✔"
  else
    # name the half-pair case explicitly, since a bare file test misses it
    local half=""
    for candidate in id_ed25519 id_ecdsa id_rsa; do
      if [[ -f "$key_dir/$candidate" || -f "$key_dir/$candidate.pub" ]]; then
        half="$candidate"; break
      fi
    done

    if [[ -n "$half" ]]; then
      echo "   ✋ ssh key ~/.ssh/$half is a HALF pair" >&2
      echo "      ⇒ a private half with no .pub cannot be registered with a remote;" >&2
      echo "        a .pub with no private half cannot be presented to one. either" >&2
      echo "        looks like 'a key exists' and fails at the first connection" >&2
      echo "      fix: derive the public half from the private one —" >&2
      echo "        ssh-keygen -y -f ~/.ssh/$half > ~/.ssh/$half.pub" >&2
    else
      echo "   ✋ this box holds NO ssh keypair" >&2
      echo "      ⇒ it can present no identity, so an ssh git remote and every" >&2
      echo "        box-to-box hop are refused by the far end" >&2
      echo "      fix (local):  rhx grove.provision --what 2.3.ssh --mode apply" >&2
      echo "      fix (grove):  read plan.grove-credentials.md — a grove's key is" >&2
      echo "        provisioned deliberately, never generated by an install" >&2
    fi
    failed=$(( failed + 1 ))
  fi

  ####################################################################
  # 2. the private half's mode — ssh refuses an over-readable key outright
  ####################################################################
  if [[ -n "$found" ]]; then
    local mode; mode="$(stat -c '%a' "$key_dir/$found" 2>/dev/null || echo "")"
    # only the owner may read or write — 600, or 400 for a read-only key
    if [[ "$mode" == "600" || "$mode" == "400" ]]; then
      echo "   • private key mode $mode — owner only ✔"
    else
      echo "   ✋ ~/.ssh/$found has mode '$mode', which ssh REFUSES" >&2
      echo "      ⇒ ssh prints 'UNPROTECTED PRIVATE KEY FILE' and ignores the key" >&2
      echo "        entirely, so the symptom is 'the remote asks for a password'" >&2
      echo "        rather than 'the key file is $mode'. a cp -r of a dotfile tree" >&2
      echo "        is the usual cause" >&2
      echo "      fix: chmod 600 ~/.ssh/$found" >&2
      failed=$(( failed + 1 ))
    fi
  fi

  [[ "$failed" -eq 0 ]] || return 1
}
