#!/usr/bin/env bash
######################################################################
# .what = the open-hours gate — a reconciler, its systemd user unit, and a
#         timer that re-asks the policy twice an hour
#
#   inside the declared window the GLOBAL commit and radio gates are closed;
#   outside it they are open. the SCHEDULE is declared below; the clock math
#   lives in `src/machine/machine_openhours_reconcile`
#
# .why
#   - 🛑 it is OPT-IN: a gate enacts a human's PREFERENCE, never a fact about the
#     box, so `GROVE_OPENHOURS_ENABLED` is the whole switch
#   - ⚠️ opt-out TEARS DOWN, where `6.apps` merely skips — a stale live timer that
#     blocks commits is worse than an absent one. and it opens NO gate: the safe
#     direction on an unreconciled gate is closed
#   - ⚠️ the flag is a REPO edit, never an `--include` — a gate a human must
#     re-request forever is a gate they will lose
#   - 🛑 it OWNS a linked dir: `rhx` reads skills off `$cwd/.agent/`, the gate
#     skills call `require_git_repo`, and no pushed checkout on a grove is a repo
#   - it lives in 5.devtools, where its `rhx` and node dependencies already are
#   - it declines nowhere: a grove left open while the laptop closes is the gate
#     with a hole in it
#
# .refs = howdoes.the-openhours-gate-converges.md — every .why above, in full
#
# usage:
#   rhx grove.provision --what 5.18.openhours --mode apply
######################################################################

# the cwd the reconciler stands in — ONE declaration, read by the payload, the
# upsert, and the verify alike. BAKED off `$HOME`, so it is the same sentence on
# every box and no pointer file can drift from it
GROVE_OPENHOURS_CWD="$HOME/.local/state/machine_openhours/cwd"

# the SCHEDULE — ONE declaration, read by both halves and by the payload through
# the file rendered below. it lives in the REPO, since a config edited on the box
# is lost at the next apply (`rule.require.repo-as-source-of-truth`)
# ⚠️ the DAYS are a contiguous RANGE, so `mon,tue,thu` is INEXPRESSIBLE — a split
#    week needs this to grow a set parser first
GROVE_OPENHOURS_ENABLED=true
GROVE_OPENHOURS_DAYS="1-5"             # iso weekdays, mon=1 .. sun=7, contiguous
GROVE_OPENHOURS_FROM="08:00"           # inclusive
GROVE_OPENHOURS_TILL="20:00"           # exclusive
GROVE_OPENHOURS_ZONE="America/Chicago"

# the rendered copy the PAYLOAD reads. it runs from `~/.local/bin`, outside any
# checkout, so it cannot source this file — see the render below
GROVE_OPENHOURS_SCHEDULE="$HOME/.local/state/machine_openhours/schedule.env"

# .what = is the declared schedule well formed? stdout names the first fault
# .why  = ONE reader, so the upsert and the verify cannot cut the set two ways
#   (`gotcha.a-check-that-cries-wolf-gets-silenced`, m.9)
# 🛑 the zone is checked as a FILE, never via `date` — a typo'd TZ exits 0 in UTC
# ⚠️ `10#` on the times: bash reads `0800` as OCTAL
grove_provision_5_18_openhours_schedule_check() {
  local lo hi
  [[ "$GROVE_OPENHOURS_DAYS" =~ ^([1-7])-([1-7])$ ]] || {
    echo "days '$GROVE_OPENHOURS_DAYS' is no contiguous iso range — expected e.g. '1-5'"
    return 1
  }
  lo="${BASH_REMATCH[1]}"; hi="${BASH_REMATCH[2]}"
  [[ "$lo" -le "$hi" ]] || {
    echo "days '$GROVE_OPENHOURS_DAYS' runs backward — a range wraps no week"
    return 1
  }

  [[ "$GROVE_OPENHOURS_FROM" =~ ^([01][0-9]|2[0-3]):[0-5][0-9]$ ]] || {
    echo "from '$GROVE_OPENHOURS_FROM' is no HH:MM clock time"; return 1; }
  [[ "$GROVE_OPENHOURS_TILL" =~ ^([01][0-9]|2[0-3]):[0-5][0-9]$ ]] || {
    echo "till '$GROVE_OPENHOURS_TILL' is no HH:MM clock time"; return 1; }
  [[ $((10#${GROVE_OPENHOURS_FROM//:/})) -lt $((10#${GROVE_OPENHOURS_TILL//:/})) ]] || {
    echo "from '$GROVE_OPENHOURS_FROM' is not before till '$GROVE_OPENHOURS_TILL'"
    return 1
  }

  [[ -f "/usr/share/zoneinfo/$GROVE_OPENHOURS_ZONE" ]] || {
    echo "zone '$GROVE_OPENHOURS_ZONE' names no file under /usr/share/zoneinfo"
    return 1
  }
}

# .what = the schedule as the payload reads it
# .why  = ONE renderer, so the upsert WRITES and the verify DIFFS one text
grove_provision_5_18_openhours_schedule_render() {
  cat <<EOF
# GENERATED by: rhx grove.provision --what 5.18.openhours --mode apply
# the declaration lives in src/grove.provision/5.devtools/5.18.openhours/_.sh
# an edit here is overwritten by the next apply
OPENHOURS_DAYS=$GROVE_OPENHOURS_DAYS
OPENHOURS_FROM=$GROVE_OPENHOURS_FROM
OPENHOURS_TILL=$GROVE_OPENHOURS_TILL
OPENHOURS_ZONE=$GROVE_OPENHOURS_ZONE
EOF
}

# the role packages the gate skills come from — PINNED, since this dir is never
# re-resolved and a float would split two boxes a month apart
GROVE_OPENHOURS_ROLE_PKGS=(
  "rhachet-roles-ehmpathy@1.38.12"   # git.commit.uses
  "rhachet-roles-bhuild@0.21.36"     # radio.uses
)

# the two skill paths the cwd must carry, relative to it
GROVE_OPENHOURS_SKILL_COMMIT=".agent/repo=ehmpathy/role=mechanic/skills/git.commit/git.commit.uses.sh"
GROVE_OPENHOURS_SKILL_RADIO=".agent/repo=bhuild/role=dispatcher/skills/radio.uses.sh"

# .what = which of THREE states is the reconciler's cwd in? whole|half|absent
# .why a state, never a boolean, so the upsert and the verify share one fact
#   rather than cut the same set two ways (`gotcha.a-check-that-cries-wolf`, m.9)
# 🛑 it reads the installed VERSION, never mere presence — drift off the pin
#   reads `half`, and the upsert rebuilds (defect shape 6)
#
# stdout: whole = a git repo, both packages AT THE PIN, both gate skills on disk
#         half  = the dir exists and one of those does not hold
#         absent = never built
grove_provision_5_18_openhours_cwd_state() {
  local dir="$GROVE_OPENHOURS_CWD" spec name want have
  [[ -d "$dir" ]] || { echo absent; return 0; }
  [[ -d "$dir/.git" ]] || { echo half; return 0; }

  for spec in "${GROVE_OPENHOURS_ROLE_PKGS[@]}"; do
    name="${spec%@*}"
    want="${spec##*@}"
    have="$(jq -r '.version // empty' "$dir/node_modules/$name/package.json" 2>/dev/null)"
    [[ "$have" == "$want" ]] || { echo half; return 0; }
  done

  [[ -r "$dir/$GROVE_OPENHOURS_SKILL_COMMIT" ]] || { echo half; return 0; }
  [[ -r "$dir/$GROVE_OPENHOURS_SKILL_RADIO"  ]] || { echo half; return 0; }
  echo whole
}

grove_provision_5_18_openhours() {
  bundle.upgrade 5.18.openhours.provision.upsert
  bundle.upgrade 5.18.openhours.provision.verify
}
