#!/usr/bin/env bash
######################################################################
# .what = the robot brains — claude-code, rhachet, and codex, plus their config
#
# .why no phase CALLS another
#   - a delegated install-then-configure reports the CONFIG's status only (`rule.forbid.failhide`)
#   - each phase returns its own status (`rule.require.bundle-as-sole-declaration`)
#
# .why every machine, no decline — a grove runs the brains too
#
# usage:
#   rhx grove.provision --what 5.3.brains --mode apply
######################################################################

####################################################################
# the pins — ONE each, read by BOTH halves, so a second literal cannot drift
#
# .the criterion = WHO CAN PUBLISH
#   - first-party (rhachet, declastruct) floats; third-party (codex, claude-code) is pinned
#   - a pin moves when a human MOVES it, and the verify asks the BINARY
#
# .how to bump = a decision, so two steps, never one:
#   npm view @openai/codex version
#   codex --version
#
# .refs = gotcha.5-3-brains-pins.demo=publish-path-and-drift.md
####################################################################
GROVE_BRAIN_CLAUDE_PIN="2.1.280"
GROVE_BRAIN_CODEX_PIN="0.128.0"

####################################################################
# the CANDIDATE claude — `claude.latest`, a parallel install the default never sees
#   - `claude` stays the pin; a human trials a newer cli without moving it
#   - 🔴 the shim is `claude.latest`, NEVER `claude`, which would become the default
#   - ⚠️ set the pin ONLY while a trial is live; "" tears the candidate down
#   - the memory cap RESTATES `claude()` in `2.7.aliases/bash_aliases.sh` — bump BOTH
# .refs = define.5-3-brains.candidate-claude
####################################################################
GROVE_BRAIN_CLAUDE_LATEST_PIN=""               # "" = opted out; torn down next apply
GROVE_BRAIN_CLAUDE_LATEST_PREFIX="$HOME/.local/opt/claude"
GROVE_BRAIN_CLAUDE_LATEST_SHIM="$HOME/.local/bin/claude.latest"
GROVE_BRAIN_CLAUDE_LATEST_MEMMAX="8G"

# .what = which of THREE states is the candidate in? one reader for both halves
# .why the PIN, never a dir test — a run cut partway leaves a dir with no binary
#   (`define.provision-defect-shapes`, shape 6)
#
# stdout: whole  = the pinned prefix holds a runnable bin AND `latest` names it
#         half   = something under the prefix exists and one of those does not
#         absent = never built
grove_provision_5_3_brains_claude_latest_state() {
  local dir="$GROVE_BRAIN_CLAUDE_LATEST_PREFIX/v$GROVE_BRAIN_CLAUDE_LATEST_PIN"

  [[ -d "$GROVE_BRAIN_CLAUDE_LATEST_PREFIX" ]] || { echo absent; return 0; }
  [[ -x "$dir/node_modules/.bin/claude" ]] || { echo half; return 0; }
  [[ "$(readlink "$GROVE_BRAIN_CLAUDE_LATEST_PREFIX/latest" 2>/dev/null)" == "v$GROVE_BRAIN_CLAUDE_LATEST_PIN" ]] \
    || { echo half; return 0; }
  echo whole
}

# .what = the shim, ONE renderer, so the upsert WRITES and the verify DIFFS one text
# .why it names `latest`, not the pinned dir, and runs `/bin/sh` (.refs "the shim renderer")
grove_provision_5_3_brains_claude_latest_shim_render() {
  cat <<EOF
#!/bin/sh
# GENERATED by: rhx grove.provision --what 5.3.brains --mode apply
# the declaration lives in src/grove.provision/5.devtools/5.3.brains/_.sh
# an edit here is overwritten by the next apply
#
# .what = run the CANDIDATE claude, capped, without touching the pinned default
bin="\$HOME/.local/opt/claude/latest/node_modules/.bin/claude"

if [ ! -x "\$bin" ]; then
  echo "✋ the candidate claude is absent at \$bin" >&2
  echo "   fix: rhx grove.provision --what 5.3.brains --mode apply" >&2
  exit 1
fi

# one path: the capped launch — the same one the \`claude\` shell function takes
# in 2.7.aliases/bash_aliases.sh. wait out a revive in flight (bundle
# 1.6.5.usermanager restarts a dead manager in ~2s); a manager that stays mute
# is a defect, so say so and stop rather than run uncapped
i=0
until systemctl --user show-environment >/dev/null 2>&1; do
  i=\$((i + 1))
  if [ "\$i" -ge 10 ]; then
    echo "✋ your user systemd manager does not answer on \\\$XDG_RUNTIME_DIR/bus" >&2
    echo "   fix: sudo -v && rhx grove.provision --what 1.6.5.usermanager --mode apply" >&2
    exit 1
  fi
  sleep 0.5
done

exec systemd-run --user --scope --quiet --collect \\
  --slice=claude.slice \\
  -p MemoryMax=$GROVE_BRAIN_CLAUDE_LATEST_MEMMAX \\
  "\$bin" "\$@"
EOF
}

# .what = converge the candidate — its prefix, the `latest` pointer, and the shim.
#   the pinned default is untouched by every line here
grove_provision_5_3_brains_claude_latest_upsert() {

  local prefix="$GROVE_BRAIN_CLAUDE_LATEST_PREFIX"
  local shim="$GROVE_BRAIN_CLAUDE_LATEST_SHIM"
  local pin="$GROVE_BRAIN_CLAUDE_LATEST_PIN"

  # opted out — TEAR DOWN, never skip (.refs "opt in, opt out")
  if [[ -z "$pin" ]]; then
    if [[ -e "$shim" || -d "$prefix" ]]; then
      rm -f "$shim" || return 1
      rm -rf "$prefix" || return 1
      echo "   🌙 claude.latest is opted out — its shim and prefixes removed"
    else
      echo "   🌙 claude.latest is opted out — no candidate installed"
    fi
    echo "      opt in: set GROVE_BRAIN_CLAUDE_LATEST_PIN in this bundle's _.sh"
    return 0
  fi

  # 1. the versioned prefix, guarded by the three-valued reader
  local dir="$prefix/v$pin"
  local state
  state="$(grove_provision_5_3_brains_claude_latest_state)"

  if [[ "$state" == "whole" ]]; then
    echo "   • claude.latest is built at the declared candidate ($pin)"
  else
    mkdir -p "$dir" || return 1

    # WRITTEN, never `pnpm init`, with its build approval inside (.refs "the package.json")
    cat > "$dir/package.json" <<'EOF' || return 1
{
  "name": "claude-latest",
  "private": true,
  "pnpm": {
    "onlyBuiltDependencies": ["@anthropic-ai/claude-code"]
  }
}
EOF

    # `web_pnpm` — an unbounded registry call holds the duct (`rule.require.bounded-probes-in-verifies`)
    if ! ( cd "$dir" && web_pnpm add "@anthropic-ai/claude-code@$pin" ); then
      echo "   ✋ could not install the candidate claude@$pin" >&2
      echo "      ⇒ the pinned default is untouched; only the candidate is absent" >&2
      echo "      read why: cd $dir && pnpm add @anthropic-ai/claude-code@$pin" >&2
      return 1
    fi
    echo "   • claude.latest candidate installed ✔ ($pin)"
  fi

  # 2. the `latest` pointer — `-n`, or a bump lands inside the old target (.refs "`ln -sfn`")
  ln -sfn "v$pin" "$prefix/latest" || {
    echo "   ✋ could not point $prefix/latest at v$pin" >&2
    echo "      ⇒ the shim reads the pointer, so it would run the prior candidate" >&2
    return 1
  }

  # 3. REAP every prefix the pin no longer names (.refs "the reap of undeclared prefixes")
  local stale reaped=0
  for stale in "$prefix"/v*; do
    [[ -d "$stale" ]] || continue
    [[ "$(basename "$stale")" == "v$pin" ]] && continue
    rm -rf "$stale" || {
      echo "   ✋ could not reap the undeclared candidate prefix $stale" >&2
      return 1
    }
    echo "   • reaped an undeclared candidate prefix → $(basename "$stale")"
    reaped=1
  done
  [[ "$reaped" -eq 1 ]] || true

  # 4. the shim, RENDERED, so the verify can diff it
  mkdir -p "$(dirname "$shim")" || return 1
  grove_provision_5_3_brains_claude_latest_shim_render > "$shim" || {
    echo "   ✋ could not write the claude.latest shim to $shim" >&2
    return 1
  }
  chmod +x "$shim" || return 1
  echo "   • claude.latest shim declared → $shim"
}

# .what = prove the candidate matches the tree, and that nothing in ~/.local/bin
#   has displaced the pinned default. READ-ONLY
grove_provision_5_3_brains_claude_latest_verify() {
  local failed=0

  # 🔴 a `claude` in ~/.local/bin would BECOME the default — asked on every run
  #    (.refs "why the shim is `claude.latest` and never `claude`")
  if [[ -e "$HOME/.local/bin/claude" ]]; then
    echo "   ✋ a file named 'claude' sits in ~/.local/bin" >&2
    echo "      ⇒ that dir outranks \$PNPM_HOME/bin in a human's shell, so this" >&2
    echo "        file — not the declared pin — is what 'claude' now runs" >&2
    echo "      ⇒ every pin check above still reads the pnpm copy, so it is" >&2
    echo "        green on a box whose claude was swapped out from under it" >&2
    echo "      ⇒ the candidate is reached as 'claude.latest' for exactly this" >&2
    echo "        reason; no bundle here writes a 'claude' to this dir" >&2
    echo "      fix: rm $HOME/.local/bin/claude" >&2
    failed=1
  fi

  # the claim INVERTS with the pin: opted out, residue is the defect (.refs "opt in, opt out")
  local latest_prefix="$GROVE_BRAIN_CLAUDE_LATEST_PREFIX"
  local latest_shim="$GROVE_BRAIN_CLAUDE_LATEST_SHIM"
  local latest_pin="$GROVE_BRAIN_CLAUDE_LATEST_PIN"

  if [[ -z "$latest_pin" ]]; then
    if [[ -e "$latest_shim" || -d "$latest_prefix" ]]; then
      echo "   ✋ claude.latest is opted out and the box still carries it" >&2
      echo "      ⇒ shim: ${latest_shim} $([[ -e "$latest_shim" ]] && echo present || echo absent)" >&2
      echo "      ⇒ prefix: ${latest_prefix} $([[ -d "$latest_prefix" ]] && echo present || echo absent)" >&2
      echo "      fix: rhx grove.provision --what 5.3.brains --mode apply" >&2
      failed=1
    else
      echo "   • claude.latest is opted out, and no candidate is installed ✔"
      echo "     opt in: set GROVE_BRAIN_CLAUDE_LATEST_PIN in this bundle's _.sh"
    fi
    return $failed
  fi

  # 1. the install, by the SAME reader the upsert guards on
  local latest_state
  latest_state="$(grove_provision_5_3_brains_claude_latest_state)"

  if [[ "$latest_state" != "whole" ]]; then
    echo "   ✋ the claude.latest candidate reads '$latest_state', not 'whole'" >&2
    echo "      ⇒ expected a runnable bin at $latest_prefix/v$latest_pin, with" >&2
    echo "        '$latest_prefix/latest' naming it" >&2
    echo "      ⇒ found: latest → $(readlink "$latest_prefix/latest" 2>/dev/null || echo '(no symlink)')" >&2
    echo "      fix: rhx grove.provision --what 5.3.brains --mode apply" >&2
    failed=1
  else
    echo "   • claude.latest candidate is built at $latest_pin ✔ (latest → v$latest_pin)"
  fi

  # 2. the shim is CURRENT — diffed against a fresh render, never a presence test
  if [[ ! -x "$latest_shim" ]]; then
    echo "   ✋ the claude.latest shim is absent or not executable" >&2
    echo "      ⇒ looked for: $latest_shim" >&2
    echo "      fix: rhx grove.provision --what 5.3.brains --mode apply" >&2
    failed=1
  elif ! grove_provision_5_3_brains_claude_latest_shim_render | diff -q - "$latest_shim" >/dev/null 2>&1; then
    echo "   ✋ the claude.latest shim has drifted from this checkout" >&2
    echo "      ⇒ it may still name a prior target or a prior memory cap" >&2
    echo "      read the diff: diff <(…render…) $latest_shim" >&2
    echo "      fix: rhx grove.provision --what 5.3.brains --mode apply" >&2
    failed=1
  else
    echo "   • the claude.latest shim matches this checkout ✔"
  fi

  # 3. the SHIM runs and the BINARY answers (.refs "the verify runs the shim")
  if [[ -x "$latest_shim" ]]; then
    local latest_live
    latest_live="$(timeout -k 5 "$GROVE_BRAIN_PROBE_SECONDS" "$latest_shim" --version 2>/dev/null \
      | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || true)"

    if [[ -z "$latest_live" ]]; then
      echo "   🌙 claude.latest ran, but did not answer a version this run"
      echo "      ⇒ the candidate ($latest_pin) is unproven here, not disproven"
    elif [[ "$latest_live" == "$latest_pin" ]]; then
      echo "   • claude.latest is $latest_live, the declared candidate ✔"
    else
      echo "   ✋ claude.latest is $latest_live, but the declared candidate is $latest_pin" >&2
      echo "      ⇒ the candidate drifted, so a trial reports on a version the" >&2
      echo "        tree does not name — and a comparison against the pin is then" >&2
      echo "        one nobody else can reproduce" >&2
      echo "      fix: rhx grove.provision --what 5.3.brains --mode apply" >&2
      echo "      or, if the drift is wanted: bump GROVE_BRAIN_CLAUDE_LATEST_PIN first" >&2
      failed=1
    fi

    # 4. REACH — a 🌙, since this shell's PATH is not the human's
    local latest_which
    latest_which="$(command -v claude.latest 2>/dev/null || true)"
    if [[ "$latest_which" == "$latest_shim" ]]; then
      echo "   • claude.latest is on PATH ✔"
    else
      echo "   🌙 claude.latest is installed and this shell's PATH does not name it"
      echo "      ⇒ found: ${latest_which:-(no match)}"
      echo "      ⇒ ~/.local/bin reaches PATH from ~/.zshenv (owned by 2.5.zsh), so"
      echo "        a shell that read neither rc will not see it — unproven here"
    fi
  fi

  return $failed
}

grove_provision_5_3_brains() {
  bundle.upgrade 5.3.brains.provision.upsert
  bundle.upgrade 5.3.brains.provision.verify
  bundle.upgrade 5.3.brains.configure.upsert
  bundle.upgrade 5.3.brains.configure.verify
}
